version: '2'
services:

  redis:
    image: redis:3.0
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    logging:
      driver: none
    networks:
      app_net:
        ipv4_address: 172.16.238.9

  elasticsearch:
    image: elasticsearch:2.3
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    logging:
      driver: none
    networks:
      app_net:
        ipv4_address: 172.16.238.4
    volumes:
     - ./data:/usr/share/elasticsearch/data

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
